name: papers
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  device_preview: ^1.0.0
  flutter_staggered_grid_view: ^0.5.0
  sliding_up_panel: ^2.0.0+1
  flutter_map: ^0.14.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/logo.png

  fonts: 
    - family: Comfortaa
      fonts:
        - asset: assets/font/Comfortaa/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/font/Comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/font/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/font/Comfortaa/Comfortaa-Regular.ttf
        - asset: assets/font/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600

  